paths:
  project_root: "."
  data:
    root: "data"
    raw: "data/raw"
    dataset_zip: "data/raw/dataset_14_punti_pulito_06072023.zip"
    dataframe_master: "data/dataframe_master.csv"
    dataset_dir: "data/dataset" # cartella 'dataset' (compare quando viene estratto dataset_zip)
  src:
    root: "src"
    models: "src/models"
    utils: "src/utils"